name: Release & Test

on:
  push:
    branches:
    - '**'
  delete:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - name: Release
      uses: satackey/push-prebuilt-action@v0.2.0-beta3
      with:
        push-branch: '{branch}-release'

  # 
  # test built image caching

  test_saving_built:
    runs-on: ubuntu-latest
    needs:
    - build_and_push

    steps:
    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - uses: actions/checkout@v2
      name: Pull action
      with:
        ref: ${{ steps.extract.outputs.branch }}-release
        path: action-dlc

    - uses: actions/checkout@v2

    - uses: ./action-dlc
      with:
        repotag: test_project_node
        key: test_project_node-docker-image-sha-${{ github.sha }}

    - run: docker-compose -f test_project/docker-compose.yml -p test_project build

  test_restoring_built:
    runs-on: ubuntu-latest
    needs:
    - test_saving_built

    steps:
    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - uses: actions/checkout@v2
      name: Pull action
      with:
        ref: ${{ steps.extract.outputs.branch }}-release
        path: action-dlc

    - uses: actions/checkout@v2

    - uses: ./action-dlc
      with:
        repotag: test_project_node
        key: test_project_node-docker-image-sha-${{ github.sha }}

    - run: echo ::set-output name=id::$(docker image ls -q test_project_node)
      id: cached

    - run: docker-compose -f test_project/docker-compose.yml -p test_project build

    - run: echo ::set-output name=id::$(docker image ls -q test_project_node)
      id: latest

    - run: |
        if [ ! ${{ steps.cached.outputs.id }} = ${{ steps.latest.outputs.id }} ];then
          echo cached != latest
          exit 1
        fi

  # 
  # test pulled image caching

  test_saving_pulled:
    runs-on: ubuntu-latest
    needs:
    - build_and_push

    steps:
    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - uses: actions/checkout@v2
      name: Pull action
      with:
        ref: ${{ steps.extract.outputs.branch }}-release
        path: action-dlc

    - uses: ./action-dlc
      with:
        repotag: amazon/aws-cli
        key: aws-cli-docker-image-sha-${{ github.sha }}

    - run: docker run --rm amazon/aws-cli --version

  test_restoring_pulled:
    runs-on: ubuntu-latest
    needs:
    - test_saving_pulled

    steps:
    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - uses: actions/checkout@v2
      name: Pull action
      with:
        ref: ${{ steps.extract.outputs.branch }}-release
        path: action-dlc

    - uses: ./action-dlc
      with:
        repotag: amazon/aws-cli
        key: aws-cli-docker-image-sha-${{ github.sha }}

    - run: docker inspect amazon/aws-cli
    - run: echo ::set-output name=id::$(docker image ls -q amazon/aws-cli)
      id: cached

    - run: docker pull amazon/aws-cli

    - run: docker inspect amazon/aws-cli
    - run: echo ::set-output name=id::$(docker image ls -q amazon/aws-cli)
      id: latest

    - run: |
        if [ ! ${{ steps.cached.outputs.id }} = ${{ steps.latest.outputs.id }} ];then
          echo cached != latest
          exit 1
        fi
