name: README sample test

on:
  push:
    branches:
    - '**'
    tags:
    - v0.0
    paths:
    - .github/workflows/test_readme.yml
jobs:
  no_cache_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0
    - run: docker-compose -f test_project/docker-compose.yml -p test_project build

  cached_build:
    runs-on: ubuntu-latest
    needs:
    - no_cache_build

    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0

    - name: Get cached image ID
      run: echo ::set-output name=id::$(docker image ls -q test_project_node)
      id: cached

    - run: docker-compose -f test_project/docker-compose.yml -p test_project build

    - name: Show built image ID
      run: echo ::set-output name=id::$(docker image ls -q test_project_node)
      id: latest

    - name: Compare cached ID and after build ID
      run: |
        if [ ! '${{ steps.cached.outputs.id }}' = '${{ steps.latest.outputs.id }}' ];then
          echo cached != latest
          exit 1
        fi

